# Generated by Django 2.2.6 on 2022-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='med1a/', verbose_name='Картинка'),
        ),
    ]
